backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "/src/uploads" # Media files will be stored in the repo 
public_folder: "/uploads"
collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    files:
      - label: "Home Page"
        name: "home"
        file: "src/_pages/home.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: "body", name: "body", widget: markdown }
          - { label: "Services", name: "services", widget: markdown }
          - label: "Featured Image"
            name: "featured-image"
            widget: "image"
            choose_url: true
            media_library:
              config:
                multiple: false
          - label: 'Profile picture'
            name : "profile-pic"
            widget: "image"
            choose_url: true
            media_library:
              config:
                multiple: false
          - label: "End of life support list"
            name: eol-support
            widget: markdown
          - label: "Sensory curation list"
            name: sensory-curation
            widget: markdown
          - label: "Education list"
            name: education
            widget: markdown
          - label: "section 3"
            name: "section3"
            widget: markdown
          - label: "secion 3 image"
            name: "section3-pic"
            widget: "image"
      - label: "About Page"
        name: "about"
        file: "src/_pages/about.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Badge", name: "badge", widget: "code", required: false, output_code_only: true }
          - label: "Featured Image"
            name: "featured-image"
            widget: "image"
            choose_url: true
            media_library:
              config:
                multiple: false
      - label: "Resources Page"
        name: "resources"
        file: "src/_pages/resources.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
