backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "/src/uploads" # Media files will be stored in the repo 
public_folder: "/uploads"
collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    files:
      - label: "Home Page"
        name: "home"
        file: "src/_pages/home.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: "Badge", name: "badge", widget: "code", required: false, output_code_only: true }
          - { label: Intro, name: intro, widget: markdown }
          - { label: "body", name: "body", widget: markdown }
          - { label: "credentials", name: "credentials", widget: markdown }
          - { label: "Services", name: "services", widget: markdown }
          - label: "End of life support"
            name: eol-support
            widget: markdown
          - label: "Sensory curation"
            name: sensory-curation
            widget: markdown
          - label: "Education"
            name: education
            widget: markdown
      - label: "About Page"
        name: "about"
        file: "src/_pages/about.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Badge", name: "badge", widget: "code", required: false, output_code_only: true }
      - label: "Services Page"
        name: "services"
        file: "src/_pages/services.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
